@startuml
skinparam linetype polyline
hide circle
hide stereotype
!include ./style.iuml


    class "**Concept**" as C<<TM>> {
        |_ identifier[WHOCommon] 1..*   
        |_ status 1..1
        |_ name 1..1
        |_ title 1..1
        |_ definition 1..1
        |_ identifier[other] 0..*
        |_ designation 0..*
        |_ property 0..*
          |_ key 1..1
          |_ value 0..1
        --
    }

    class "**Data Dictionary**" as G<<TM>> {
        |_ identifier 1..*   
        |_ name 1..1
        |_ title 1..1
        |_ owner 1..*
        |_ version 1..1
        |_ concept 0..*
        --
    }

C "*" -o "1" G :"               "


legend
Data needs 
for concepts
(see [[./diagram_legend.html#data-object-details-with-plantuml legend]])
endlegend


@enduml