@startuml
'skinparam linetype ortho
skinparam linetype polyline
hide circle
hide stereotype

'!pragma layout smetana

skinparam class<<MD>> {
 BorderColor DarkSlateGray
 BackgroundColor WhiteSmoke
 HeaderBackgroundColor #909090
}

skinparam class<<TM>> {
 BorderColor #505090
 BackgroundColor APPLICATION
 HeaderBackgroundColor #8bd
}


class "**Form**" as F<<TM>> {
    |_ identifier[SG] 1..*   
    |_ url 1..*   
    |_ status 1..1
    |_ name 1..1
    |_ title 1..1
    |_ experimental 1..1    
    |_ description 1..1
    |_ item 1..*   
      |_ item 0..*  
    --
}


class "**Modular form**" as MF<<TM>> {
}
class "**ValueSet**" as VS<<TM>> {
}


F - MF : "  Reuses  "

'P -- C : "  obeys  "

'C -u[hidden]- X 

'ED -r[hidden]- C : "                   "

F -- VS : "  Contains  "


@enduml