@startuml
skinparam linetype polyline
hide circle
hide stereotype
!include ./style.iuml


    class "**Persona**" as Pers<<TM>> {
        |_ identifier 1..*   
        |_ status 1..1
        |_ name 1..1
        |_ title 1..1
'        |_ type = 'person'
'        |_ experimental 1..1    
        |_ description 1..1  
        --
    }


legend
Data needs 
for personas
(see [[./diagram_legend.html#data-object-details-with-plantuml legend]])
endlegend

@enduml