@startuml
skinparam linetype polyline
hide circle
hide stereotype
!include ./style.iuml


    class "**Scenario**" as Scenario<<TM>> {
        |_ identifier 1..*   
        |_ status 1..1
        |_ name 1..1
        |_ title 1..1
        |_ description 1..1  
        |_ actor 1..*
        |_ step 1..1
          |_ initiator 0..1
          |_ receiver 0..1
          |_ activity 0..1
          |_ description 0..1  
        --
    }

legend
Data needs 
for scenarios
(see [[./diagram_legend.html#data-object-details-with-plantuml legend]])
endlegend


@enduml