@startuml
skinparam linetype polyline
hide circle
hide stereotype
!include ./style.iuml


class "**Requirement Set**" as RS<<TM>> {
    |_ identifier 1..*   
    |_ status 1..1
    |_ name 1..1
    |_ title 1..1
    |_ description 1..1
    |_ activityId 1..1  
    |_ category 0..*
    --
}

class "**Requirement**" as R<<TM>> {
    |_ identifier 1..*   
    |_ category 0..*
    |_ strength 0..1
    --
}

class "**Functional**\n**Requirement**" as FR<<TM>> {
    |_ process 1..*
    |_ persona 1..*
    |_ description 1..1  
      |_ text 1..1  
      |_ functionality 1..1  
      |_ goal 1..1  
    --
}

class "**Non-Functional**\n**Requirement**" as NFR<<TM>> {
    |_ description 1..1  
      |_ text 1..1  
    --
}

R -u-* RS
FR -u-|> R
NFR -u-|> R


legend
Data needs 
for requirements
(see [[./diagram_legend.html#data-object-details-with-plantuml legend]])
endlegend


@enduml