@startuml
'skinparam linetype ortho
skinparam linetype polyline
hide circle
hide stereotype
!include ./style.iuml


    class "**  Logical Model  **" as LM<<TM>> {
        |_ identifier 1..*   
        |_ status 1..1
        |_ name 1..1
        |_ element 1..*
          |_ short 1..1
          |_ definition 1..1
          |_ type 1..1
          |_ binding 0..1
          |_ comment 0..1
          |_ constraint 0..1
          |_ code 1..1   
          |_ code[other]
            |_ system 1..1
            |_ code 1..1
            |_ comments 0..1
            |_ relationship 0..1  
        --
    }

    class "**  Logical Model  **" as LMP<<TM>> {
    }
 
     class "**  Logical Model  **" as LMD<<TM>> {
    }


 class "**    Logical Model    **" as LMR<<TM>> {
    }

LM -u-|> LMP : "\n\n   Specializes  \n " 
LM -r- LMD : "       Uses         "
'LMP -r- LMR : "     "

LM -u- LMR : "Ref."  


LMP -r[hidden]-|> LMR : "                      "
LMR -D[hidden]- LMD : "      \n\n\n\n\n  "
'LM -u- LMR : "                "

legend
Data needs 
for logical models
(see [[./diagram_legend.html#data-object-details-with-plantuml legend]])
endlegend


@enduml
