@startuml
skinparam linetype polyline
hide circle
hide stereotype
!include ./style.iuml


class "**StrutureMap**" as StructureMap<<TM>> {
    |_ identifier 1..*   
    |_ status 1..1
    |_ name 1..1
    |_ title 1..1
    |_ description 1..1
    --
}

footer
Data needs for
structure maps
(see [[./diagram_legend.html#data-object-details-with-plantuml legend]])
endfooter



@enduml