@startuml
skinparam linetype polyline
hide circle
hide stereotype
!include ./style.iuml


class "**StrutureMap**" as StructureMap<<TM>> {
    |_ identifier 1..*   
    |_ status 1..1
    |_ name 1..1
    |_ title 1..1
    |_ description 1..1
    --
}

@enduml