@startuml
skinparam linetype ortho
'skinparam linetype polyline
hide circle
hide stereotype
!include ./style.iuml


class "**Disease**" as D <<TM>>{
  |_ code
  |_ designation
  |_ matching_codes  
    |_ system
    |_ code   
  |_ active
  --
}

class "**Vaccine**"  as V <<TM>>{
  |_ code
  |_ designation
  |_ matching_codes  
    |_ system
    |_ code 
  |_ active
  --
}

class "**VaccineType**" as VT<<TM>>{
  |_ code
  |_ designation
  |_ matching_codes   
    |_ system
    |_ code 
  |_ is_live_vaccine
  |_ active
  --
}

D -d-> V
V -r-> VT: "             "



@enduml



