@startuml
skinparam linetype polyline
hide circle
hide stereotype
!include ./style.iuml


class "**Disease**" as D <<TM>>{
  |_ code
  |_ designation
  |_ matching_codes  
    |_ system
    |_ code   
  |_ active
  --
}

class "**Vaccine**"  as V <<TM>>{
  |_ code
  |_ designation
  |_ matching_codes  
    |_ system
    |_ code 
  |_ is_type
  |_ is_live
  |_ active
  --
}

D <-r- V: "targets"



@enduml



