@startuml
'skinparam linetype ortho
skinparam linetype polyline
hide circle
hide stereotype

'!pragma layout smetana

skinparam class<<MD>> {
 BorderColor DarkSlateGray
 BackgroundColor WhiteSmoke
 HeaderBackgroundColor #909090
}

skinparam class<<TM>> {
 BorderColor #505090
 BackgroundColor APPLICATION
 HeaderBackgroundColor SkyBlue
}


class "**Disease**" as D <<TM>>{
  |_ code
  |_ designation
  |_ matching_codes  
    |_ system
    |_ code   
  |_ active
  --
}

class "**Vaccine**"  as V <<TM>>{
  |_ code
  |_ designation
  |_ matching_codes  
    |_ system
    |_ code 
  |_ is_type
  |_ is_live
  |_ active
  --
}

D <-r- V: "targets"



@enduml



